table mapping_TenureGrp
	lineageTag: d9eaa098-28c5-48e4-bafb-166a15ce8e16

	column Tenure_in_Months
		dataType: int64
		formatString: 0
		lineageTag: 80648c69-fdc0-44f7-bf7f-d1c2a287a4e5
		summarizeBy: none
		sourceColumn: Tenure_in_Months

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Tenure Group'
		dataType: string
		lineageTag: a8267510-3ba4-4e5a-868a-4ef0e14e9d18
		summarizeBy: none
		sourceColumn: Tenure Group
		sortByColumn: 'Tenure Grp Sorting'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Tenure Grp Sorting'
		dataType: int64
		formatString: 0
		lineageTag: 4335675a-936a-4736-9ae9-737019a74f86
		summarizeBy: none
		sourceColumn: Tenure Grp Sorting

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition mapping_TenureGrp = m
		mode: import
		source = ```
				let
				    Source = prod_Churn,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Tenure_in_Months"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates"),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates1", "Tenure Group", each if [Tenure_in_Months] < 6 then "< 6 Months" else if 
				[Tenure_in_Months] < 12 then "6-12 months" else if 
				[Tenure_in_Months] < 18 then "12-18 months" else if 
				[Tenure_in_Months] < 24 then "18-24 months" else ">=24 months"),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Tenure Grp Sorting", each if [Tenure Group] = "< 6 Months" then 1 else if [Tenure Group] = "6-12 months" then 2 else if [Tenure Group] = "12-18 months" then 3 else if [Tenure Group] = "18-24 months" then 4 else 5),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Tenure Grp Sorting", Int64.Type}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"Tenure Grp Sorting", Int64.Type}})
				in
				    #"Changed Type"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

